// Package ai generates AI tool configuration files for RyxoGo projects.
// Run automatically by `rxgo new` and `rxgo init`.
// Keeps Cursor, Claude Code, Codex, and Copilot perfectly aligned.
package ai

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Generator creates AI tool config files for a RyxoGo project
type Generator struct {
	root    string
	appName string
}

// NewGenerator creates a generator for the project at root
func NewGenerator(root, appName string) *Generator {
	return &Generator{root: root, appName: appName}
}

// GenerateAll creates all AI config files
func (g *Generator) GenerateAll() error {
	files := map[string]func() (string, error){
		".cursorrules":          g.cursorRules,
		"CLAUDE.md":             g.claudeMD,
		"AGENTS.md":             g.agentsMD,
		".github/copilot.md":    g.copilotMD,
		".ryxogo/context.md":    g.ryxogoContext,
		".ryxogo/mcp.json":      g.mcpConfig,
		".ryxogo/schema.json":   g.schemaPlaceholder,
	}

	for path, fn := range files {
		content, err := fn()
		if err != nil {
			return fmt.Errorf("generating %s: %w", path, err)
		}

		fullPath := filepath.Join(g.root, path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return err
		}
	}

	return nil
}

// cursorRules generates .cursorrules for Cursor AI
func (g *Generator) cursorRules() (string, error) {
	return fmt.Sprintf(`# RyxoGo Project Rules for Cursor
# Auto-generated by rxgo — do not edit manually
# Re-generate with: rxgo ai sync
# Generated: %s

## Framework
This project uses RyxoGo — a Go-first frontend framework that compiles to WebAssembly.
NOT React. NOT Vue. NOT any JavaScript framework.

## MCP Connection
This project has a RyxoGo MCP server. Connect to it at: http://localhost:7777
Start it with: rxgo mcp serve

ALWAYS call get_app_schema before generating any code.
ALWAYS call list_types before creating new types to avoid duplicates.
ALWAYS call validate_component after generating a component.

## Project: %s

## File Structure
pages/          → Route components (file = URL)
components/     → Reusable UI components  
stores/         → Global state
types/          → Shared Go types
public/         → Static assets

## Component Pattern — ALWAYS follow this exactly

  type ComponentName struct {
      rx.Base               // for components
      // OR rx.Page         // for page-level components
      Props ComponentNameProps
      // signals go here (lowercase)
      count *rx.Signal[int]
      users *rx.AsyncSignal[[]User]
  }

  func (c *ComponentName) Setup() {
      c.count = rx.Use(0)
      c.users = rx.Async(func() ([]User, error) {
          return rx.Get[[]User]("/api/users")
      })
  }

  func (c *ComponentName) Render() *rx.Node {
      if c.users.IsLoading() { return Spinner{}.Render() }
      if c.users.IsError()   { return ErrorCard{}.Render() }
      return rx.Div(rx.Props{Class: "..."},
          // ... UI tree
      )
  }

## Signal Rules
- ALWAYS declare signals in Setup(), never in Render()
- Use rx.Use(value) for local state
- Use rx.Async(fn) for data fetching — NEVER raw goroutines
- Use rx.Computed(fn) for derived values — NO dependency arrays
- Read with .Val(), write with .Set(), never assign directly

## Element Builders
rx.Div, rx.Span, rx.P, rx.H1, rx.H2, rx.H3
rx.Button, rx.Input, rx.Form, rx.Img, rx.A
rx.Ul, rx.Li, rx.Nav, rx.Header, rx.Main, rx.Footer
rx.Text("content")           — text node
rx.If(cond, yes, no)         — conditional
rx.Each(items, func(...))    — list rendering

## Props struct
  rx.Props{
      Class:       "tailwind classes here",
      ID:          "element-id",
      Style:       map[string]string{"color": "red"},
      OnClick:     func() { ... },
      OnInput:     func(v string) { ... },
      Value:       "input value",
      Placeholder: "hint text",
      Disabled:    false,
      Type:        "text",
  }

## HTTP
  // In Setup() only:
  rx.Get[ResponseType]("/api/endpoint")
  rx.Post[ResponseType]("/api/endpoint", body)
  rx.Fetch("/api/endpoint").Bearer(token).Param("k","v").DoJSON(&result)

## Routing
  // pages/index.go      → /
  // pages/about.go      → /about
  // pages/users/[id].go → /users/:id
  p.Param("id")    // route param
  p.Query("q")     // query string
  rx.Navigate("/path")

## NEVER DO THESE
- Never use useState, useEffect, or any React concepts
- Never write JavaScript
- Never use fmt.Println in Render()
- Never assign to signal directly: c.count = 5 ✗  →  c.count.Set(5) ✓
- Never fetch in Render() — only in Setup()
- Never create a type that already exists in types/
- Never use float64/int32 etc — let Go infer types from rx.Use()
`, time.Now().Format("2006-01-02"), g.appName), nil
}

// claudeMD generates CLAUDE.md for Claude Code
func (g *Generator) claudeMD() (string, error) {
	return fmt.Sprintf(`# %s — RyxoGo Project

> Auto-generated by RyxoGo. Re-generate with: rxgo ai sync

## What is this project?

A frontend web application built with **RyxoGo** — a Go-first framework
that compiles to WebAssembly. The developer experience is similar to React
but everything is Go, not JavaScript.

## MCP Server (use this first!)

RyxoGo includes an MCP server that gives you live access to the project structure.

Start it:
  rxgo mcp serve

Available tools:
  - get_app_schema        → full project structure
  - get_component(name)   → source + schema for any component  
  - get_page(name)        → source + schema for any page
  - list_routes           → all URL routes
  - list_types            → all shared types
  - validate_component    → check generated code before writing
  - get_ryxogo_docs(topic)→ framework docs (signals/routing/fetching/stores)
  - generate_component_scaffold → starter code

## Core Concepts

### Signals (state)
  count := rx.Use(0)              // local signal
  count.Val()                     // read
  count.Set(5)                    // write → re-render

  total := rx.Computed(func() int { return count.Val() * 2 })

  rx.Watch(func() {               // side effect
      fmt.Println(count.Val())    // auto-tracked
  })

### Async Data
  users := rx.Async(func() ([]User, error) {
      return rx.Get[[]User]("/api/users")
  })
  // Then in Render():
  if users.IsLoading() { ... }
  if users.IsError()   { ... }
  data := users.Data()

### Component Structure
  type MyPage struct {
      rx.Page
      count *rx.Signal[int]
  }
  func (p *MyPage) Setup()           { p.count = rx.Use(0) }
  func (p *MyPage) Render() *rx.Node { return rx.Div(...) }

## Workflow for new features

1. Call get_app_schema to understand existing structure
2. Call list_types to check for existing types
3. Call get_ryxogo_docs("signals") etc for API reference
4. Generate the component
5. Call validate_component to verify syntax
6. Write to the correct file

## Commands
  rxgo serve        — dev server with hot reload
  rxgo build        — build to WASM
  rxgo mcp serve    — start MCP server
  rxgo generate     — scaffold a component
  rxgo ai sync      — regenerate AI config files
`, g.appName), nil
}

// agentsMD generates AGENTS.md for OpenAI Codex and similar
func (g *Generator) agentsMD() (string, error) {
	return fmt.Sprintf(`# AGENTS.md — %s
# RyxoGo Framework Project
# For: OpenAI Codex, GitHub Copilot Workspace, and other agent tools

## Setup

Before writing any code, start the RyxoGo MCP server:
  rxgo mcp serve &

Then call: GET http://localhost:7777/schema
This returns the complete app structure as JSON.

## Language & Framework

- Language: Go (not JavaScript, not TypeScript)
- Framework: RyxoGo (not React, not Vue, not Angular)
- Target: WebAssembly (GOARCH=wasm)
- Import: rx "github.com/ryxogo/ryxogo"

## Required Patterns

### Every component MUST follow this structure:

  package components  // or pages, stores

  import rx "github.com/ryxogo/ryxogo"

  type [Name]Props struct {   // omit if no props
      FieldName Type
  }

  type [Name] struct {
      rx.Base           // use rx.Page for pages
      Props [Name]Props // omit if no props
      // private signals:
      fieldName *rx.Signal[Type]
  }

  func (c *[Name]) Setup() {
      c.fieldName = rx.Use(initialValue)
  }

  func (c *[Name]) Render() *rx.Node {
      return rx.Div(rx.Props{Class: "..."}, ...)
  }

## Rules

1. NEVER write JavaScript
2. NEVER use React hooks or patterns
3. ALWAYS use rx.Async() for API calls, never goroutines in Render()
4. ALWAYS call list_types before creating new types
5. ALWAYS validate generated code with validate_component
6. Signals ONLY in Setup(), never in Render()
7. .Val() to read, .Set() to write — never direct assignment

## File Routing Convention

  pages/index.go         → /
  pages/about.go         → /about
  pages/blog/index.go    → /blog
  pages/blog/[slug].go   → /blog/:slug
  pages/users/[id].go    → /users/:id

## Testing

  rxgo build 2>&1          — check for compile errors
  rxgo validate ./...      — validate all components
`, g.appName), nil
}

// copilotMD generates GitHub Copilot configuration
func (g *Generator) copilotMD() (string, error) {
	return fmt.Sprintf(`# GitHub Copilot Configuration
# Project: %s
# Framework: RyxoGo (Go → WebAssembly)

This is a RyxoGo project. Key patterns:

1. State: rx.Use() signals, not useState
2. Components: Go structs with Setup() and Render()
3. Fetching: rx.Async() with IsLoading()/IsError()/Data()
4. Routing: file-based in pages/ directory
5. Elements: rx.Div(), rx.Button(), rx.Text() etc — not JSX
`, g.appName), nil
}

// ryxogoContext generates .ryxogo/context.md — the master reference
func (g *Generator) ryxogoContext() (string, error) {
	return `# RyxoGo Framework — AI Context Reference

This file is the authoritative reference for AI tools working in RyxoGo projects.

## Quick API Reference

### Signals
  rx.Use(v)              → *Signal[T]          local state
  rx.Computed(fn)        → *Computed[T]        derived state  
  rx.Watch(fn)           → *Effect             side effects
  rx.Async(fn)           → *AsyncSignal[T]     async data

### Elements
  rx.Div(props, children...)
  rx.Span(props, children...)
  rx.P(props, children...)
  rx.H1/H2/H3(props, children...)
  rx.Button(props, children...)
  rx.Input(props)              — self-closing
  rx.Form(props, children...)
  rx.Img(props)                — self-closing
  rx.A(props, children...)
  rx.Text("content")           — text node
  rx.If(cond, yes, no)
  rx.IfOnly(cond, node)
  rx.Each(items, fn)           → []*Node
  rx.Nodes(slice)              — flatten to children

### Props
  rx.Props{
      Class, ID, Style, Attrs,
      OnClick, OnInput, OnChange, OnSubmit,
      Value, Placeholder, Disabled, Checked,
      Type, Src, Alt, Href,
  }

### HTTP
  rx.Get[T](url)               → (T, error)
  rx.Post[T](url, body)        → (T, error)
  rx.Put[T](url, body)         → (T, error)
  rx.Del(url)                  → error
  rx.Fetch(url).Method().Header().Bearer().Body().Param().Do()
  rx.Fetch(url).DoJSON(&v)

### Router
  rx.Navigate(path)
  rx.Back()
  p.Param("key")               — route :param
  p.Query("key")               — ?key=value

### App
  app := rx.New()
  app.Route("/path", &PageComponent{})
  app.MountTo("app")           — default: #app
  app.Run()

## Component Lifecycle Order
  1. Struct instantiated
  2. Setup() called — declare all signals here
  3. Render() called — return virtual DOM
  4. OnMount() called — component is in DOM
  5. [state changes → Render() called again]
  6. OnUnmount() called — component leaving DOM
`, nil
}

// mcpConfig generates .ryxogo/mcp.json for MCP client configuration
func (g *Generator) mcpConfig() (string, error) {
	return fmt.Sprintf(`{
  "name": "%s",
  "framework": "ryxogo",
  "version": "1.0.0",
  "mcp": {
    "server": "http://localhost:7777",
    "startCommand": "rxgo mcp serve",
    "tools": [
      "get_app_schema",
      "get_component",
      "get_page",
      "list_routes",
      "list_types",
      "validate_component",
      "get_conventions",
      "get_ryxogo_docs",
      "generate_component_scaffold"
    ]
  },
  "cursor": {
    "rulesFile": ".cursorrules",
    "mcpEnabled": true
  },
  "claude": {
    "contextFile": "CLAUDE.md",
    "mcpEnabled": true
  },
  "codex": {
    "agentsFile": "AGENTS.md"
  }
}`, g.appName), nil
}

// schemaPlaceholder creates an empty schema file that gets populated by rxgo mcp serve
func (g *Generator) schemaPlaceholder() (string, error) {
	return fmt.Sprintf(`{
  "_note": "This file is auto-generated by rxgo mcp serve. Do not edit.",
  "_generated": "%s",
  "name": "%s",
  "framework": "ryxogo",
  "routes": [],
  "components": [],
  "pages": [],
  "stores": [],
  "types": []
}`, time.Now().Format(time.RFC3339), g.appName), nil
}

// UpdateSchema re-scans the project and writes the latest schema to .ryxogo/schema.json
func UpdateSchema(root string) error {
	// This is called by rxgo mcp serve on startup and file changes
	schemaPath := filepath.Join(root, ".ryxogo", "schema.json")

	lines := strings.Builder{}
	lines.WriteString(fmt.Sprintf(`{
  "_note": "Auto-generated by rxgo mcp serve. Updated: %s",
  "framework": "ryxogo"
}`, time.Now().Format(time.RFC3339)))

	return os.WriteFile(schemaPath, []byte(lines.String()), 0644)
}
